<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\SharedLibrary\Common.Dapper\Common.Dapper.csproj" />
    <ProjectReference Include="..\Email.Dto\Email.Dto.csproj" />
  </ItemGroup>

</Project>
