<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>a433a8e5-e599-4086-949e-fad2f1ab723f</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..\..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Uploads\DemandOfJusticeDocs\**" />
    <Content Remove="Uploads\DemandOfJusticeDocs\**" />
    <EmbeddedResource Remove="Uploads\DemandOfJusticeDocs\**" />
    <None Remove="Uploads\DemandOfJusticeDocs\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.20.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.7.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Common.Repository\Common.Repository.csproj" />
    <ProjectReference Include="..\..\..\SharedLibrary\Core\Core.csproj" />
    <ProjectReference Include="..\..\Auth\JwtAuthenticationManager\JwtAuthenticationManager.csproj" />
    <ProjectReference Include="..\Case.Dto\Case.Dto.csproj" />
    <ProjectReference Include="..\Case.ServiceBus\Case.ServiceBus.csproj" />
  </ItemGroup>

</Project>
