<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>c7376e5e-452f-4f89-88b8-96487ecca864</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..\..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Auth\CommonMethods.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.1" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.20.1" />
    <PackageReference Include="Select.HtmlToPdf.NetCore" Version="24.1.0" />
    <PackageReference Include="Serilog" Version="4.2.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="9.0.0" />
    <PackageReference Include="Serilog.Sinks.Async" Version="2.1.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
    <PackageReference Include="Serilog.Sinks.MSSqlServer" Version="8.1.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.7.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Common.Repository\Common.Repository.csproj" />
    <ProjectReference Include="..\..\..\SharedLibrary\Core\Core.csproj" />
    <ProjectReference Include="..\..\Auth\JwtAuthenticationManager\JwtAuthenticationManager.csproj" />
    <ProjectReference Include="..\Master.Dto\Master.Dto.csproj" />
    <ProjectReference Include="..\Master.ServiceBus\Master.ServiceBus.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Auth\" />
    <Folder Include="Uploads\CircularOrder\" />
    <Folder Include="Uploads\UserManual\" />
  </ItemGroup>

  <ProjectExtensions><VisualStudio><UserProperties appsettings_1json__JsonSchema="" /></VisualStudio></ProjectExtensions>

</Project>
