<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>3295b586-410d-4cdb-b400-e6e2591f701a</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Controllers\SSOIntegrationController.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCoreRateLimit" Version="5.0.0" />
    <PackageReference Include="ExcelDataReader.DataSet" Version="3.7.0" />
    <PackageReference Include="Microsoft.AspNetCore.Cors" Version="2.2.0" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.20.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.8.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\SharedLibrary\Core.Insfrastructure\Core.Insfrastructure.csproj" />
    <ProjectReference Include="..\..\SharedLibrary\Core\Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="CSS\" />
    <Folder Include="Logs\ErrorLog\" />
    <Folder Include="Templates\" />
  </ItemGroup>

</Project>
