<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Report.Dto\Report.Dto.csproj" />
    <ProjectReference Include="..\Report.Repository\Report.Repository.csproj" />
  </ItemGroup>

</Project>
